- src/Fbx2Raw.cpp
- src/Raw2Gltf.cpp
- src/RawModel.cpp
- src/RawModel.h
- src/glTF/ImageData.cpp
- src/main.cpp
- src/utils/File_Utils.cpp
- src/utils/File_Utils.h
- src/utils/Image_Utils.h
- src/utils/String_Utils.h
- Move towards std::string over char * and FbxString where convenient,
- Make a clear distinction between textures whose image files have been
located and those who haven't; warn early in the latter case.
- Extend RawTexture so we always know logical name in FBX, original file
name in FBX, and inferred location in local filesystem.
- In non-binary mode, simply output the inferred local file basename as
the URI; this will be the correct relative path as long as the texture
files are located next to the .gltf and .bin files.
Primary remaining urge for a follow-up PR:
- We should be copying texture image files into the .gltf output folder,
but before that we should switch to an off-the-shelf cross-platform
file manipulation library like https://github.com/cginternals/cppfs.
When we make that …
> Further improvemens to texture resolution.

- src/main.cpp
In the FBX world, (0, 0) is generally the lower left. By the glTF specification, (0, 0) is the upper left. The only recourse is to literally flip all texture files (generally unwise) or to remap the UV space.
Is this confusing in an artist-to-engineer workflow? Maybe. But it's the best option, and it seems reasonably easy to communicate.
To request unflipped coordinates, send in a --no-flip-v command switch.
> Default to vertically flipping texture coordinates.

- src/Raw2Gltf.cpp
- src/Raw2Gltf.h
- src/main.cpp
- src/utils/File_Utils.cpp
- src/utils/File_Utils.h
When we've successfully located a referenced texture image on the local filesystem and we're generating non-binary, non-embedded output, copy the source texture wholesale into the destination directory.
This means the output folder is always a full, free-standing deployment, one that can be dragged into e.g. https://gltf-viewer.donmccurdy.com/
This is surely far from the quickest way to copy a file, but it's effortlessly cross-platform and whether the process takes 10 or 20 milliseconds seems mostly irrelevant for a command line tool. This is really all just placeholder for C++17 and #include <filesystem> anyway.
> Copy texture files to output dir when appropriate.

- src/Fbx2Raw.cpp
We were warnings against `eInheritRSrs`, which is actually the one type of inheritance we're good with. It's eInheritRrSs we should freak out about.
That said, no need to do it for the root node -- at that point there is no global transform to worry about.
Partially fixes https://github.com/facebookincubator/FBX2glTF/issues/27.
> Fix and improve inheritance warnings.

- npm/index.js
Cross-platform development is the best!
> Use .exe suffix on Windows.

- README.md
- src/Raw2Gltf.cpp
- src/Raw2Gltf.h
- src/main.cpp
The FBX SDK absolutely claims that there is a normal layer to each FbxShape, with non-trivial data, even when the corresponding FBX file, upon visual inspection, explicitly contains nothing but zeroes. The only conclusion I can draw is that the SDK is computing normals from geometry, without being asked to, which seems kind of sketchy.
These computed normals are often not at all what the artist wanted, they take up a lot of space -- often pointlessly, since if they're computed, we could just as well compute them on the client -- and at least in the case of three.js their inclusion uses up many of the precious 8 morph target slots in the shader.
So, they are now opt-in, at least until we can solve the mystery of just what goes on under the hood in the SDK.
> Make blend shape normals/tangents opt-in.

- src/Fbx2Raw.cpp
- src/Raw2Gltf.cpp
- src/RawModel.cpp
- src/RawModel.h
I've changed the code to allow several node shares the same mesh.
- Use the FbxMesh::GetUniqueID() as surface identificator, instead of associating to a node name.
- Each RawNode instance has an Id of the associated surface.
- Modify the gltf genereation to assign surfaces to nodes.
Here you can find a test to test that feature:
https://drive.google.com/open?id=1CKbDGCX2wSo8VpP07vwLsEjuEZxftc3K
It produces only 1 mesh, and 5 nodes that uses the same mesh.
Best regards,
David Ávila
> Modify FBX2glTF to allow that several nodes share the same mesh.

- CMakeLists.txt
- README.md
- src/Fbx2Raw.cpp
- src/Raw2Gltf.cpp
- src/RawModel.cpp
- src/RawModel.h
- src/glTF/MaterialData.cpp
- src/glTF/MaterialData.h
There is no formal support for PBR parameters in FBX, but the Stingray PBS material export path gets pretty close:
- It's free with Maya, so a large proportion of artists have access to it,
- It's how Allegorithmic's Substance Painter exports (when coupled with Maya),
- It actually takes advantage FBX's extensible and hierarchical property system. Other solutions have been more arcane,
So, long story short, we can now finally both read and write PBR models.
This feature necessitated some internal refactoring, and more may be needed down the road if we add more material types. The most complex new code performs the packing of multiple data channels into a single texture, e.g. metallic and roughness occupy the blue and green channels in a common texture.
In addition to the Stingray PBS …
> Support for Stingray PBS material definitions

- src/Fbx2Raw.cpp
There is a problem with the normal channel in some models.
When a transform is applied to normal, binormal & tangents, the translation must be removed from that transaform (generally casting a mat4x4 to mat3x3).
In that case I've fixed that problem in Fbx2Raw::ReadMesh(...) method.
To test that issue, you can use that model:
https://drive.google.com/open?id=10wBSADf6y9xzNA177yIbK-u7Ek5t5etC
(Made by Willi Decarpentrie: https://sketchfab.com/models/0782a88e7ad14de9bff7953005dc2c4c)
Here with errors:
With the fix applied:
Best regards,
David Ávila, Wave Engine team member
www.waveengine.net
> Fix normal issues on some models

- src/Fbx2Raw.cpp
- src/Raw2Gltf.cpp
- src/RawModel.cpp
- src/RawModel.h
This PR fix the problem caused when several nodes has the same name:
https://github.com/facebookincubator/FBX2glTF/issues/41
To fix that issue I've used the FbxNode::GetUniqueID() as node identificator, instead of identify with its node name. Because of that, every node reference that previously was associated to a name string, now is associated to a nodeId (long)
Best regards,
David Ávila, Wave Engine team member
www.waveengine.net
> Fix duplicate name issues

- src/Raw2Gltf.cpp
- src/Raw2Gltf.h
- src/RawModel.cpp
- src/RawModel.h
- src/main.cpp
This was way overdue. Breaking up large meshes into many 65535-vertex primitives can save a few bytes, but it's really a lot of complication for minor benefit.
With this change the user can force short or long indices, and the default is to use shorts for smaller meshes and longs for longer.
Fixes https://github.com/facebookincubator/FBX2glTF/issues/68.
> Add support for 32-bit indices.

- src/utils/Image_Utils.h
This is necessary at least on gcc 6.3
> Include <algorithm> in Image_Utils.h

- src/FBX2glTF.cpp
- src/fbx/Fbx2Raw.cpp
More information found here.
I tested that this commit zeroes out rotation correctly when exporting a zero transform camera from Maya.
https://forums.autodesk.com/t5/fbx-forum/90-postrotation-of-camera-and-light-nodes/m-p/4225298/highlight/true#M8467
> Fix camera rotation from FBX, fix illegal memory access of binary data

- src/fbx/Fbx2Raw.cpp
Need to do some fun checks of fbx internal camera model before computing FOV.
Useful FBXSDK example if we want to support more camera info later.
https://help.autodesk.com/view/FBX/2017/ENU/?guid=__cpp_ref__view_scene_2_set_camera_8cxx_example_html
> fix fov computation from fbxsdk

- src/fbx/Fbx2Raw.cpp
- src/fbx/FbxMaterialsAccess.cpp
- src/fbx/FbxMaterialsAccess.hpp
- src/gltf/GltfModel.hpp
- src/gltf/Raw2Gltf.cpp
- src/gltf/properties/MaterialData.cpp
- src/gltf/properties/MaterialData.hpp
- src/raw/RawModel.cpp
- src/raw/RawModel.hpp
This PR adds support for exporting user properties assigned to materials, previously ignored and missing from the glTF "extras" section.
Now an example materials section in the glTF looks like this (note: halcyonUrl):
```
"materials": [
{
"name": "Cream_Marble",
"alphaMode": "OPAQUE",
"extras": {
"fromFBX": {
"shadingModel": "<unknown>",
"isTruePBR": false,
"userProperties": {
"halcyonUrl": {
"type": "eFbxString",
"value": "Phoenix/Materials/Cream_Marble"
}
}
}
},
"pbrMetallicRoughness": {
"baseColorFactor": [
0.0274509824812412,
0.023529414087534,
0.0196078438311815,
1.0
],
"metallicFactor": 0.200000002980232,
"roughnessFactor": 0.800000011920929
}
}
],
```
> Added support for exporting user properties assigned to materials

- src/fbx/FbxSkinningAccess.cpp
Previous code would call Normalized() on a Vec4f containing the skinning weights. This normalizes the vector, i.e. makes the length of the vector equal to 1.0. For skinning weights what we want is the sum of the weights to be 1.0, which is a different. This commit fixes that.
> Fix skinning weight normalization. 

- .dockerignore
- Dockerfile
- docker-compose.yaml
This pull request dockerizes FBX2glTF and is based on the azure build file. I've included a simple `docker-compose.yaml` because I find its syntax more convenient. A few notes
* To build an image run `docker-compose build`.
* To run in the container run `docker-compose run fbx2gltf bash`. `FBX2glTF` is on the PATH, so it can be executed from anywhere.
* I attempted to use git lfs to fetch the FBX SDK, but it caused problems in managed build environments such as Docker Hub and Google Cloud Build. Instead, the Dockerfile fetches the SDK directly from Autodesk
* If this pull request is accepted, it'd be great to setup automatic builds on Docker Hub.
---
I am still finding that the latest build segfaults, but that appears to match the current build on azure. Related #183
> Dockerize FBX2glTF

- .dockerignore
- Dockerfile
I've added the sdk directory to the docker ignore. With the SDK ignored, we can install the SDK before adding the project source. This allows the docker image to preserve most of the layer caches when source code is changed.
> Added sdk to dockerignore

- appveyor.yml
This is just the Windows equivalent of https://github.com/facebookincubator/FBX2glTF/pull/200.
> Tell AppVeyor to install the FBX SDK from elsewhere

- CMakeLists.txt
The FBX SDK is compiled against a regular libiconv on Windows on Linux (with symbols libconv_open() etc) but on Mac, they compiled it against Apple's modified libiconv, which renames those functions. Annoyingly this means we need to explicitly decline the Conan libiconv package, for that platform only.
> Fix iconv on mac

- src/FBX2glTF.cpp
If the extension is `gltf` then the model directory will be set to the parent directory. If the extension is `glb` then `outputBinary` will be set to binary output.
> Write `.gltf` to parent directory & infer binary from `.glb`

- src/gltf/properties/MeshData.cpp
- src/gltf/properties/PrimitiveData.cpp
- src/gltf/properties/PrimitiveData.hpp
Very basic change modified the morph target names to output to mesh.extras.targetNames as noted in the discussion here;
https://github.com/KhronosGroup/glTF/issues/1036
... and the consequent implementation note here;
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#morph-targets
> Morph target names output to mesh.extras.targetNames
